plugins {
    id 'java'
}

allprojects {
    apply plugin: 'java'

    group = 'me.xpyex.plugin.flywithfood'
    version = '2.0.6'

    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        compileOnly 'org.jetbrains:annotations:23.0.0'
        compileOnly 'com.google.code.gson:gson:2.9.1'
    }

    processResources {
        def props = [version: version]
        inputs.properties props
        filteringCharset 'UTF-8'
        filesMatching('plugin.yml') {
            expand props
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
    }

    tasks.withType(Javadoc) {
        options.encoding = "UTF-8"
    }

    tasks.withType(Copy) {
        duplicatesStrategy 'exclude'
    }

    java {
        toolchain.languageVersion.set(JavaLanguageVersion.of(8))
    }
}