name: FlyWithFood
version: @version@
main: me.xpyex.plugin.flywithfood.bukkit.FlyWithFoodB
authors: [ XPYEX ]
description: FlyWithFood
commands:
  FlyWithFood:
    aliases:
      - fwf
      - fly
softdepend:
  - Vault