plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group 'me.xpyex.plugin.flywithfood'

dependencies {
    implementation project(":common")
    implementation project(":bukkit")
    implementation project(":sponge7")
    implementation project(":folia")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}